# Generated by Django 6.1.1 on 2026-09-08 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('category', models.CharField(max_length=100)),
                ('experience_period', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kendo.post')),
            ],
        ),
    ]
