# Generated by Django 6.1.1 on 2026-09-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('video', '動画'), ('image', '画像')], max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('nickname', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', '初心者仲間'), ('1_year', '剣道歴1年'), ('shodan', '初段'), ('nidan', '二段'), ('sandan', '三段'), ('4th_dan_plus', '四段以上'), ('instructor', '指導員・先生')], default='beginner', max_length=20)),
                ('video_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kendo.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
