# Generated by Django 6.1.1 on 2026-09-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendo', '0002_seed_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=50, verbose_name='スコア')),
                ('summary', models.TextField(verbose_name='分析結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='kendo.post', verbose_name='投稿')),
            ],
            options={
                'verbose_name': 'AI分析',
                'verbose_name_plural': 'AI分析',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='投稿者')),
                ('body', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kendo.post', verbose_name='投稿')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['created_at'],
            },
        ),
    ]
